# Generated by Django 2.0.12 on 2020-03-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicqr',
            name='author',
        ),
    ]
