# Generated by Django 2.0.12 on 2020-03-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200326_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicqr',
            name='qr_type',
        ),
        migrations.RemoveField(
            model_name='staticqr',
            name='qr_type',
        ),
    ]
