# Generated by Django 2.0.12 on 2020-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200326_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('user_image_url', models.CharField(max_length=600, verbose_name='User Image Url')),
                ('phone_mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email id')),
            ],
        ),
    ]
