# Generated by Django 2.0.12 on 2020-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of QR'),
        ),
    ]
